language: ruby

rvm:
  - 1.8.7

script: "rake spec SPEC_OPTS='--color --format documentation'"

branches:
  only:
    - master
    - development
    - fixing_tests

notifications:
  email: false

gemfile: Gemfile

env:
  - PUPPET_VERSION=2.7.23 # latest 2.7; PE 2.8.0+
  - PUPPET_VERSION=3.3.2 # latest 3.3; 

before_install:
  - travis_retry gem update --system 2.1.11
  - travis_retry gem install bundler --pre
  - gem --version
  - bundle --version
  